#
# MIT License
#
# Copyright(c) 2011-2019 The Maintainers of Nanvix
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

sudo: required

language: C

services:
- docker

env:
  global:
      - MOUNT_DIR=/root/nanvix/hal

jobs:
  include:
    # Build Debug
    - stage: "Build Debug"
      name: "QEMU OpenRISC"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-openrisc /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-openrisc && export TOOLCHAIN_DIR=/root/toolchain/or1k/bin && make distclean && make contrib && make all"
    - stage: "Build Debug"
      name: "OpTiMSoC"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-openrisc /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=optimsoc && export TOOLCHAIN_DIR=/root/toolchain/or1k/bin && make distclean && make contrib && make all"
    - stage: "Build Debug"
      name: "QEMU x86"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-i486 /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-x86 && export TOOLCHAIN_DIR=/root/toolchain/i486/bin && make distclean && make contrib && make all"
    - stage: "Build Debug"
      name: "QEMU RISC-V 32-Bit"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-riscv32 /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-riscv32 && export TOOLCHAIN_DIR=/root/toolchain/riscv32/bin && make distclean && make contrib && make all"

    # Build Release
    - stage: "Build Release"
      name: "QEMU OpenRISC"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-openrisc /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-openrisc && export TOOLCHAIN_DIR=/root/toolchain/or1k/bin && export RELEASE=true && make distclean && make contrib && make all"
    - stage: "Build Release"
      name: "OpTiMSoC"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-openrisc /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=optimsoc && export TOOLCHAIN_DIR=/root/toolchain/or1k/bin && export RELEASE=true && make distclean && make contrib && make all"
    - stage: "Build Release"
      name: "QEMU x86"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-i486 /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-x86 && export TOOLCHAIN_DIR=/root/toolchain/i486/bin && export RELEASE=true && make distclean && make contrib && make all"
    - stage: "Build Release"
      name: "QEMU RISC-V 32-Bit"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-riscv32 /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-riscv32 && export TOOLCHAIN_DIR=/root/toolchain/riscv32/bin && export RELEASE=true && make distclean && make contrib && make all"

notifications:
  slack: nanvix:31ePVjsrXynUajPUDqy6I0hp
